config/routes.rb
ThinkSafe::Application.routes.draw do

  resources :rses

  resources :values

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'

  resources :stocks

  resources :prices

  resources :volumes

  resources :rsis

  resources :smas

   root :to => "stocks#index"

   match ':controller(/:action(/:id(.:format)))'
end

app/views/values/_form.html.erb
<%= form_for(@value) do |f| %>
  <% if @value.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@value.errors.count, "error") %> prohibited this value from being saved:</h2>

      <ul>
      <% @value.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/values/edit.html.erb
<h1>Editing value</h1>

<%= render 'form' %>

<%= link_to 'Show', @value %> |
<%= link_to 'Back', values_path %>

app/views/values/index.html.erb
<h1>Listing values</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @values.each do |value| %>
  <tr>
    <td><%= link_to 'Show', value %></td>
    <td><%= link_to 'Edit', edit_value_path(value) %></td>
    <td><%= link_to 'Destroy', value, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Value', new_value_path %>

app/views/values/new.html.erb
<h1>New value</h1>

<%= render 'form' %>

<%= link_to 'Back', values_path %>

app/views/values/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_value_path(@value) %> |
<%= link_to 'Back', values_path %>