config/routes.rb
ThinkSafe::Application.routes.draw do

  resources :rses

  resources :values

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'

  resources :stocks

  resources :prices

  resources :volumes

  resources :rsis

  resources :smas

   root :to => "stocks#index"

   match ':controller(/:action(/:id(.:format)))'
end

app/models/stock.rb
class Stock < ActiveRecord::Base
	has_many :prices

	has_many :volumes

	has_many :rsis

	has_many :smas
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  # GET /stocks
  # GET /stocks.xml
  def index
    @stocks = Stock.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @stocks }
    end
  end

  # GET /stocks/1
  # GET /stocks/1.xml
  def show
    @stock = Stock.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @stock }
    end
  end

  # GET /stocks/new
  # GET /stocks/new.xml
  def new
    @stock = Stock.new

     @stock.name = params[:name]
     @stock.code = params[:code]
     @stock.save

  end

  # GET /stocks/1/edit
  def edit
    @stock = Stock.find(params[:id])
  end

  # POST /stocks
  # POST /stocks.xml
  def create
    @stock = Stock.new(params[:stock])

    respond_to do |format|
      if @stock.save
        format.html { redirect_to(@stock, :notice => 'Stock was successfully created.') }
        format.xml  { render :xml => @stock, :status => :created, :location => @stock }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @stock.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /stocks/1
  # PUT /stocks/1.xml
  def update
    @stock = Stock.find(params[:id])

    respond_to do |format|
      if @stock.update_attributes(params[:stock])
        format.html { redirect_to(@stock, :notice => 'Stock was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @stock.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.xml
  def destroy
    @stock = Stock.find(params[:id])
    @stock.destroy

    respond_to do |format|
      format.html { redirect_to(stocks_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/_form.html.erb
<%= form_for(@stock) do |f| %>
  <% if @stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% @stock.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing stock</h1>

<%= render 'form' %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<h1>Listing stocks</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stocks.each do |stock| %>
  <tr>
    <td><strong><%= stock.name%></strong></td>
    <td><%= link_to 'Show', stock %></td>
    <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
    <td><%= link_to 'Destroy', stock, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Stock', new_stock_path %>

app/views/stocks/new.html.erb
<%= form_tag('/stocks/new') %>

	<h1>Add a Stock</h1>
	Name:<br>
	<p><input type=text name=name><br><p>
	Code:<br> 
	<p><input type=text name=code><br><p>
	<input type= "submit"/>

	<%= link_to 'Back', stocks_path %>


</form>

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>