config/routes.rb
ThinkSafe::Application.routes.draw do

  resources :rses

  resources :values

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'

  resources :stocks

  resources :prices

  resources :volumes

  resources :rsis

  resources :smas

   root :to => "stocks#index"

   match ':controller(/:action(/:id(.:format)))'
end

app/models/volume.rb
class Volume < ActiveRecord::Base
	belongs_to :stock
end

app/controllers/volumes_controller.rb
class VolumesController < ApplicationController
  # GET /volumes
  # GET /volumes.xml
  def index
    @volumes = Volume.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @volumes }
    end
  end

  # GET /volumes/1
  # GET /volumes/1.xml
  def show
    @volume = Volume.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @volume }
    end
  end

  # GET /volumes/new
  # GET /volumes/new.xml
  def new
    @volume = Volume.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @volume }
    end
  end

  # GET /volumes/1/edit
  def edit
    @volume = Volume.find(params[:id])
  end

  # POST /volumes
  # POST /volumes.xml
  def create
    @volume = Volume.new(params[:volume])

    respond_to do |format|
      if @volume.save
        format.html { redirect_to(@volume, :notice => 'Volume was successfully created.') }
        format.xml  { render :xml => @volume, :status => :created, :location => @volume }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @volume.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /volumes/1
  # PUT /volumes/1.xml
  def update
    @volume = Volume.find(params[:id])

    respond_to do |format|
      if @volume.update_attributes(params[:volume])
        format.html { redirect_to(@volume, :notice => 'Volume was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @volume.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /volumes/1
  # DELETE /volumes/1.xml
  def destroy
    @volume = Volume.find(params[:id])
    @volume.destroy

    respond_to do |format|
      format.html { redirect_to(volumes_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/volumes_helper.rb
module VolumesHelper
end

app/views/volumes/_form.html.erb
<%= form_for(@volume) do |f| %>
  <% if @volume.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@volume.errors.count, "error") %> prohibited this volume from being saved:</h2>

      <ul>
      <% @volume.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/volumes/edit.html.erb
<h1>Editing volume</h1>

<%= render 'form' %>

<%= link_to 'Show', @volume %> |
<%= link_to 'Back', volumes_path %>

app/views/volumes/index.html.erb
<h1>Listing volumes</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @volumes.each do |volume| %>
  <tr>
    <td><%= link_to 'Show', volume %></td>
    <td><%= link_to 'Edit', edit_volume_path(volume) %></td>
    <td><%= link_to 'Destroy', volume, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Volume', new_volume_path %>

app/views/volumes/new.html.erb
<h1>New volume</h1>

<%= render 'form' %>

<%= link_to 'Back', volumes_path %>

app/views/volumes/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_volume_path(@volume) %> |
<%= link_to 'Back', volumes_path %>